
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 12 21:05:17 CET 2017
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RIGHT_PAREN = 34;
  public static final int MULT = 3;
  public static final int CONST = 12;
  public static final int EQUALS = 40;
  public static final int INTEGER = 18;
  public static final int ARRAY = 9;
  public static final int WRITEINT = 30;
  public static final int FOR = 16;
  public static final int MINUS = 2;
  public static final int LEFT_BRACK = 36;
  public static final int NOT = 20;
  public static final int SEMICOLON = 32;
  public static final int TYPE = 26;
  public static final int OR = 22;
  public static final int COMMA = 38;
  public static final int BIGGER_THAN = 41;
  public static final int BEGIN = 10;
  public static final int IF = 17;
  public static final int WRITELN = 31;
  public static final int OF = 21;
  public static final int EOF = 0;
  public static final int BOOLEAN = 11;
  public static final int DIGITS = 6;
  public static final int RETURN = 24;
  public static final int RIGHT_BRACK = 35;
  public static final int TRUE = 4;
  public static final int error = 1;
  public static final int MODULE = 19;
  public static final int COLON = 37;
  public static final int ELSE = 14;
  public static final int WRITESTRING = 29;
  public static final int POINT = 42;
  public static final int TO = 27;
  public static final int LITERAL_STRING = 7;
  public static final int THEN = 25;
  public static final int END = 15;
  public static final int LEFT_PAREN = 33;
  public static final int FALSE = 5;
  public static final int COLON_EQUAL = 39;
  public static final int VAR = 28;
  public static final int PROCEDURE = 23;
  public static final int DO = 13;
  public static final int IDENTIFIER = 8;
}

