
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 02 17:56:57 CEST 2018
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND = 26;
  public static final int MENOR = 24;
  public static final int PUNTOYCOMA = 22;
  public static final int ELSE = 5;
  public static final int CADENA = 13;
  public static final int DEFINE = 3;
  public static final int WHILE = 12;
  public static final int RETURN = 10;
  public static final int PARIZQ = 15;
  public static final int PRINTI = 9;
  public static final int PARDER = 16;
  public static final int IF = 4;
  public static final int PRINTC = 8;
  public static final int LLAVEIZQ = 19;
  public static final int COMA = 21;
  public static final int ASIGNACION = 27;
  public static final int LLAVEDER = 20;
  public static final int DISTINTO = 25;
  public static final int EOF = 0;
  public static final int MAIN = 7;
  public static final int error = 1;
  public static final int NUMERO = 14;
  public static final int IDENTIFICADOR = 2;
  public static final int CORIZQ = 17;
  public static final int ENTERO = 6;
  public static final int CORDER = 18;
  public static final int REFERENCIA = 28;
  public static final int VOID = 11;
  public static final int MAS = 23;
}

