/* The following code was generated by JFlex 1.4.1 on 12/12/17 9:05 PM */

package compiler.lexical;

import compiler.syntax.sym;
import compiler.lexical.Token;
import es.uned.lsi.compiler.lexical.ScannerIF;
import es.uned.lsi.compiler.lexical.LexicalError;
import es.uned.lsi.compiler.lexical.LexicalErrorManager;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 12/12/17 9:05 PM from the specification file
 * <tt>/Users/colymore/branches/Uned/PL1/doc/specs/scanner.flex</tt>
 */
public class Scanner implements java_cup.runtime.Scanner, ScannerIF {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int comment = 1;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\6\1\0\1\1\1\1\22\0\1\1\1\0\1\4"+
    "\5\0\1\10\1\12\1\11\1\0\1\50\1\13\1\47\1\0\1\2"+
    "\11\3\1\36\1\37\1\0\1\45\1\46\2\0\1\21\1\31\1\26"+
    "\1\27\1\17\1\20\1\32\1\44\1\33\2\7\1\22\1\35\1\34"+
    "\1\25\1\24\1\7\1\15\1\23\1\14\1\16\1\43\1\40\1\7"+
    "\1\30\1\7\1\41\1\5\1\42\3\0\1\21\1\31\1\26\1\27"+
    "\1\17\1\20\1\32\1\44\1\33\2\7\1\22\1\35\1\34\1\25"+
    "\1\24\1\7\1\15\1\23\1\14\1\16\1\43\1\40\1\7\1\30"+
    "\1\7\1\0\1\0\uff83\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\15\4\1\11\1\12\1\4\1\13\1\14"+
    "\1\4\1\15\1\16\1\17\1\20\3\21\1\0\1\22"+
    "\1\0\1\23\1\4\1\24\11\4\1\25\1\26\1\4"+
    "\1\27\2\4\1\30\3\4\1\31\2\4\1\32\1\33"+
    "\5\4\1\34\1\4\1\35\6\4\1\36\2\4\1\37"+
    "\1\40\1\41\1\42\1\4\1\43\12\4\1\44\1\45"+
    "\1\4\1\46\1\47\4\4\1\50\3\4\1\51\4\4"+
    "\1\52\1\53\1\54\4\4\1\55\1\56\2\4\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\122\0\122\0\122\0\173\0\244\0\315"+
    "\0\366\0\122\0\122\0\122\0\u011f\0\u0148\0\u0171\0\u019a"+
    "\0\u01c3\0\u01ec\0\u0215\0\u023e\0\u0267\0\u0290\0\u02b9\0\u02e2"+
    "\0\u030b\0\u0334\0\122\0\u035d\0\122\0\122\0\u0386\0\122"+
    "\0\122\0\122\0\122\0\122\0\u03af\0\u03d8\0\244\0\122"+
    "\0\u0401\0\122\0\u042a\0\315\0\u0453\0\u047c\0\u04a5\0\u04ce"+
    "\0\u04f7\0\u0520\0\u0549\0\u0572\0\u059b\0\315\0\315\0\u05c4"+
    "\0\315\0\u05ed\0\u0616\0\315\0\u063f\0\u0668\0\u0691\0\122"+
    "\0\u06ba\0\u06e3\0\122\0\122\0\u070c\0\u0735\0\u075e\0\u0787"+
    "\0\u07b0\0\315\0\u07d9\0\315\0\u0802\0\u082b\0\u0854\0\u087d"+
    "\0\u08a6\0\u08cf\0\315\0\u08f8\0\u0921\0\315\0\315\0\315"+
    "\0\315\0\u094a\0\315\0\u0973\0\u099c\0\u09c5\0\u09ee\0\u0a17"+
    "\0\u0a40\0\u0a69\0\u0a92\0\u0abb\0\u0ae4\0\315\0\315\0\u0b0d"+
    "\0\315\0\315\0\u0b36\0\u0b5f\0\u0b88\0\u0bb1\0\315\0\u0bda"+
    "\0\u0c03\0\u0c2c\0\315\0\u0c55\0\u0c7e\0\u0ca7\0\u0cd0\0\315"+
    "\0\315\0\315\0\u0cf9\0\u0d22\0\u0d4b\0\u0d74\0\315\0\315"+
    "\0\u0d9d\0\u0dc6\0\315";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\6\1\7\1\3\1\4\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\10\1\17"+
    "\1\20\1\21\2\10\1\22\1\23\1\24\1\25\1\10"+
    "\1\26\1\10\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\10\1\40\1\41\1\42\1\43"+
    "\10\44\1\45\1\46\37\44\53\0\2\6\45\0\4\47"+
    "\1\50\1\51\43\47\2\0\2\10\3\0\1\10\4\0"+
    "\22\10\2\0\1\10\2\0\2\10\15\0\1\52\41\0"+
    "\2\10\3\0\1\10\4\0\1\10\1\53\7\10\1\54"+
    "\2\10\1\55\5\10\2\0\1\10\2\0\1\10\1\56"+
    "\6\0\2\10\3\0\1\10\4\0\3\10\1\57\16\10"+
    "\2\0\1\10\2\0\2\10\6\0\2\10\3\0\1\10"+
    "\4\0\6\10\1\60\11\10\1\61\1\10\2\0\1\10"+
    "\2\0\2\10\6\0\2\10\3\0\1\10\4\0\5\10"+
    "\1\62\3\10\1\63\10\10\2\0\1\10\2\0\2\10"+
    "\6\0\2\10\3\0\1\10\4\0\1\10\1\64\20\10"+
    "\2\0\1\10\2\0\2\10\6\0\2\10\3\0\1\10"+
    "\4\0\1\10\1\65\20\10\2\0\1\10\2\0\2\10"+
    "\6\0\2\10\3\0\1\10\4\0\1\10\1\66\2\10"+
    "\1\67\15\10\2\0\1\10\2\0\2\10\6\0\2\10"+
    "\3\0\1\10\4\0\11\10\1\70\10\10\2\0\1\10"+
    "\2\0\2\10\6\0\2\10\3\0\1\10\4\0\11\10"+
    "\1\71\10\10\2\0\1\10\2\0\2\10\6\0\2\10"+
    "\3\0\1\10\4\0\3\10\1\72\5\10\1\73\10\10"+
    "\2\0\1\10\2\0\2\10\6\0\2\10\3\0\1\10"+
    "\4\0\4\10\1\74\13\10\1\75\1\10\2\0\1\10"+
    "\2\0\2\10\6\0\2\10\3\0\1\10\4\0\11\10"+
    "\1\76\10\10\2\0\1\10\2\0\2\10\6\0\2\10"+
    "\3\0\1\10\4\0\11\10\1\77\10\10\2\0\1\10"+
    "\2\0\2\10\51\0\1\100\5\0\2\10\3\0\1\10"+
    "\4\0\1\10\1\101\20\10\2\0\1\10\2\0\2\10"+
    "\6\0\2\10\3\0\1\10\4\0\5\10\1\102\14\10"+
    "\2\0\1\10\2\0\2\10\15\0\1\103\51\0\1\104"+
    "\36\0\6\47\1\0\42\47\2\0\2\10\3\0\1\10"+
    "\4\0\2\10\1\105\17\10\2\0\1\10\2\0\2\10"+
    "\6\0\2\10\3\0\1\10\4\0\10\10\1\106\11\10"+
    "\2\0\1\10\2\0\2\10\6\0\2\10\3\0\1\10"+
    "\4\0\3\10\1\107\16\10\2\0\1\10\2\0\2\10"+
    "\6\0\2\10\3\0\1\10\4\0\1\110\21\10\2\0"+
    "\1\10\2\0\2\10\6\0\2\10\3\0\1\10\4\0"+
    "\7\10\1\111\12\10\2\0\1\10\2\0\2\10\6\0"+
    "\2\10\3\0\1\10\4\0\13\10\1\112\6\10\2\0"+
    "\1\10\2\0\2\10\6\0\2\10\3\0\1\10\4\0"+
    "\6\10\1\113\13\10\2\0\1\10\2\0\2\10\6\0"+
    "\2\10\3\0\1\10\4\0\1\10\1\114\20\10\2\0"+
    "\1\10\2\0\2\10\6\0\2\10\3\0\1\10\4\0"+
    "\1\10\1\115\20\10\2\0\1\10\2\0\2\10\6\0"+
    "\2\10\3\0\1\10\4\0\11\10\1\116\10\10\2\0"+
    "\1\10\2\0\2\10\6\0\2\10\3\0\1\10\4\0"+
    "\20\10\1\117\1\10\2\0\1\10\2\0\2\10\6\0"+
    "\2\10\3\0\1\10\4\0\16\10\1\120\3\10\2\0"+
    "\1\10\2\0\2\10\6\0\2\10\3\0\1\10\4\0"+
    "\11\10\1\121\10\10\2\0\1\10\2\0\2\10\6\0"+
    "\2\10\3\0\1\10\4\0\1\122\21\10\2\0\1\10"+
    "\2\0\2\10\6\0\2\10\3\0\1\10\4\0\1\123"+
    "\21\10\2\0\1\10\2\0\2\10\6\0\2\10\3\0"+
    "\1\10\4\0\13\10\1\124\6\10\2\0\1\10\2\0"+
    "\2\10\6\0\2\10\3\0\1\10\4\0\17\10\1\125"+
    "\2\10\2\0\1\10\2\0\2\10\6\0\2\10\3\0"+
    "\1\10\4\0\1\10\1\126\20\10\2\0\1\10\2\0"+
    "\2\10\6\0\2\10\3\0\1\10\4\0\3\10\1\127"+
    "\16\10\2\0\1\10\2\0\2\10\6\0\2\10\3\0"+
    "\1\10\4\0\3\10\1\130\16\10\2\0\1\10\2\0"+
    "\2\10\6\0\2\10\3\0\1\10\4\0\20\10\1\131"+
    "\1\10\2\0\1\10\2\0\2\10\6\0\2\10\3\0"+
    "\1\10\4\0\2\10\1\132\17\10\2\0\1\10\2\0"+
    "\2\10\6\0\2\10\3\0\1\10\4\0\3\10\1\133"+
    "\16\10\2\0\1\10\2\0\2\10\6\0\2\10\3\0"+
    "\1\10\4\0\7\10\1\134\12\10\2\0\1\10\2\0"+
    "\2\10\6\0\2\10\3\0\1\10\4\0\5\10\1\135"+
    "\14\10\2\0\1\10\2\0\2\10\6\0\2\10\3\0"+
    "\1\10\4\0\12\10\1\136\7\10\2\0\1\10\2\0"+
    "\2\10\6\0\2\10\3\0\1\10\4\0\7\10\1\137"+
    "\12\10\2\0\1\10\2\0\2\10\6\0\2\10\3\0"+
    "\1\10\4\0\17\10\1\140\2\10\2\0\1\10\2\0"+
    "\2\10\6\0\2\10\3\0\1\10\4\0\6\10\1\141"+
    "\13\10\2\0\1\10\2\0\2\10\6\0\2\10\3\0"+
    "\1\10\4\0\3\10\1\142\16\10\2\0\1\10\2\0"+
    "\2\10\6\0\2\10\3\0\1\10\4\0\2\10\1\143"+
    "\17\10\2\0\1\10\2\0\2\10\6\0\2\10\3\0"+
    "\1\10\4\0\1\144\21\10\2\0\1\10\2\0\2\10"+
    "\6\0\2\10\3\0\1\10\4\0\1\10\1\145\20\10"+
    "\2\0\1\10\2\0\2\10\6\0\2\10\3\0\1\10"+
    "\4\0\3\10\1\146\16\10\2\0\1\10\2\0\2\10"+
    "\6\0\2\10\3\0\1\10\4\0\14\10\1\147\5\10"+
    "\2\0\1\10\2\0\2\10\6\0\2\10\3\0\1\10"+
    "\4\0\3\10\1\150\16\10\2\0\1\10\2\0\2\10"+
    "\6\0\2\10\3\0\1\10\4\0\1\151\21\10\2\0"+
    "\1\10\2\0\2\10\6\0\2\10\3\0\1\10\4\0"+
    "\20\10\1\152\1\10\2\0\1\10\2\0\2\10\6\0"+
    "\2\10\3\0\1\10\4\0\3\10\1\153\16\10\2\0"+
    "\1\10\2\0\2\10\6\0\2\10\3\0\1\10\4\0"+
    "\16\10\1\154\3\10\2\0\1\10\2\0\2\10\6\0"+
    "\2\10\3\0\1\10\4\0\6\10\1\155\13\10\2\0"+
    "\1\10\2\0\2\10\6\0\2\10\3\0\1\10\4\0"+
    "\3\10\1\156\16\10\2\0\1\10\2\0\2\10\6\0"+
    "\2\10\3\0\1\10\4\0\20\10\1\157\1\10\2\0"+
    "\1\10\2\0\2\10\6\0\2\10\3\0\1\10\4\0"+
    "\13\10\1\160\6\10\2\0\1\10\2\0\2\10\6\0"+
    "\2\10\3\0\1\10\4\0\5\10\1\161\14\10\2\0"+
    "\1\10\2\0\2\10\6\0\2\10\3\0\1\10\4\0"+
    "\3\10\1\162\16\10\2\0\1\10\2\0\2\10\6\0"+
    "\2\10\3\0\1\10\4\0\3\10\1\163\16\10\2\0"+
    "\1\10\2\0\2\10\6\0\2\10\3\0\1\10\4\0"+
    "\6\10\1\164\1\165\7\10\1\166\2\10\2\0\1\10"+
    "\2\0\2\10\6\0\2\10\3\0\1\10\4\0\2\10"+
    "\1\167\17\10\2\0\1\10\2\0\2\10\6\0\2\10"+
    "\3\0\1\10\4\0\20\10\1\170\1\10\2\0\1\10"+
    "\2\0\2\10\6\0\2\10\3\0\1\10\4\0\1\10"+
    "\1\171\20\10\2\0\1\10\2\0\2\10\6\0\2\10"+
    "\3\0\1\10\4\0\20\10\1\172\1\10\2\0\1\10"+
    "\2\0\2\10\6\0\2\10\3\0\1\10\4\0\1\173"+
    "\21\10\2\0\1\10\2\0\2\10\6\0\2\10\3\0"+
    "\1\10\4\0\20\10\1\174\1\10\2\0\1\10\2\0"+
    "\2\10\6\0\2\10\3\0\1\10\4\0\1\10\1\175"+
    "\20\10\2\0\1\10\2\0\2\10\6\0\2\10\3\0"+
    "\1\10\4\0\1\10\1\176\20\10\2\0\1\10\2\0"+
    "\2\10\6\0\2\10\3\0\1\10\4\0\1\177\21\10"+
    "\2\0\1\10\2\0\2\10\6\0\2\10\3\0\1\10"+
    "\4\0\3\10\1\200\16\10\2\0\1\10\2\0\2\10"+
    "\6\0\2\10\3\0\1\10\4\0\17\10\1\201\2\10"+
    "\2\0\1\10\2\0\2\10\6\0\2\10\3\0\1\10"+
    "\4\0\20\10\1\202\1\10\2\0\1\10\2\0\2\10"+
    "\6\0\2\10\3\0\1\10\4\0\16\10\1\203\3\10"+
    "\2\0\1\10\2\0\2\10\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3567];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\3\11\4\1\3\11\16\1\1\11\1\1\2\11"+
    "\1\1\5\11\2\1\1\0\1\11\1\0\1\11\25\1"+
    "\1\11\2\1\2\11\77\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[131];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  LexicalErrorManager lexicalErrorManager = new LexicalErrorManager();
  private int commentCount = 0;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 168) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) throws LexicalError {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new LexicalError(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  throws LexicalError {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, LexicalError {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 17: 
          { /* do nothing */
          }
        case 48: break;
        case 19: 
          { commentCount++; yybegin(comment);
          }
        case 49: break;
        case 16: 
          { Token token = new Token(sym.COMMA);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 50: break;
        case 20: 
          { Token token = new Token(sym.TO);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 51: break;
        case 8: 
          { Token token = new Token(sym.MINUS);
                        token.setLine(yyline + 1);
                        token.setColumn(yycolumn + 1);
                        token.setLexema(yytext());
                        return token;
          }
        case 52: break;
        case 42: 
          { Token token = new Token(sym.BOOLEAN);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 53: break;
        case 30: 
          { Token token = new Token(sym.NOT);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 54: break;
        case 24: 
          { Token token = new Token(sym.IF);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 55: break;
        case 4: 
          { Token token = new Token(sym.IDENTIFIER);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 56: break;
        case 14: 
          { Token token = new Token(sym.BIGGER_THAN);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 57: break;
        case 47: 
          { Token token = new Token(sym.WRITESTRING);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 58: break;
        case 38: 
          { Token token = new Token(sym.CONST);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 59: break;
        case 23: 
          { Token token = new Token(sym.DO);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 60: break;
        case 43: 
          { Token token = new Token(sym.INTEGER);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 61: break;
        case 33: 
          { Token token = new Token(sym.TYPE);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 62: break;
        case 13: 
          { Token token = new Token(sym.EQUALS);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 63: break;
        case 46: 
          { Token token = new Token(sym.PROCEDURE);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 64: break;
        case 36: 
          { Token token = new Token(sym.FALSE);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 4);
                         token.setLexema(yytext());
                         return token;
          }
        case 65: break;
        case 5: 
          { Token token = new Token(sym.LEFT_PAREN);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 66: break;
        case 32: 
          { Token token = new Token(sym.TRUE);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 4);
                         token.setLexema(yytext());
                         return token;
          }
        case 67: break;
        case 18: 
          { Token token = new Token(sym.LITERAL_STRING);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext().substring(1, yytext().length() -1));
                         return token;
          }
        case 68: break;
        case 25: 
          { Token token = new Token(sym.COLON_EQUAL);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 69: break;
        case 11: 
          { Token token = new Token(sym.LEFT_BRACK);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 70: break;
        case 35: 
          { Token token = new Token(sym.ELSE);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 71: break;
        case 1: 
          { LexicalError error = new LexicalError ();
                          error.setLine(yyline + 1);
                          error.setColumn(yycolumn + 1);
                          error.setLexema(yytext());
                          lexicalErrorManager.lexicalError(error);
          }
        case 72: break;
        case 2: 
          { /* DO NOTHING */
          }
        case 73: break;
        case 22: 
          { Token token = new Token(sym.OF);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 74: break;
        case 31: 
          { Token token = new Token(sym.VAR);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 75: break;
        case 6: 
          { Token token = new Token(sym.MULT);
                        token.setLine(yyline + 1);
                        token.setColumn(yycolumn + 1);
                        token.setLexema(yytext());
                        return token;
          }
        case 76: break;
        case 21: 
          { Token token = new Token(sym.OR);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 77: break;
        case 9: 
          { Token token = new Token(sym.COLON);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 78: break;
        case 15: 
          { Token token = new Token(sym.POINT);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 79: break;
        case 3: 
          { Token token = new Token(sym.DIGITS);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 80: break;
        case 45: 
          { Token token = new Token(sym.WRITEINT);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 81: break;
        case 27: 
          { commentCount--; if(commentCount == 0) {yybegin(YYINITIAL);}
          }
        case 82: break;
        case 7: 
          { Token token = new Token(sym.RIGHT_PAREN);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 83: break;
        case 37: 
          { Token token = new Token(sym.ARRAY);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 84: break;
        case 40: 
          { Token token = new Token(sym.RETURN);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 85: break;
        case 26: 
          { commentCount++;
          }
        case 86: break;
        case 34: 
          { Token token = new Token(sym.THEN);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 87: break;
        case 44: 
          { Token token = new Token(sym.WRITELN);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 88: break;
        case 41: 
          { Token token = new Token(sym.MODULE);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 89: break;
        case 10: 
          { Token token = new Token(sym.SEMICOLON);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 90: break;
        case 12: 
          { Token token = new Token(sym.RIGHT_BRACK);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 91: break;
        case 29: 
          { Token token = new Token(sym.FOR);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 92: break;
        case 28: 
          { Token token = new Token(sym.END);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 93: break;
        case 39: 
          { Token token = new Token(sym.BEGIN);
                         token.setLine(yyline + 1);
                         token.setColumn(yycolumn + 1);
                         token.setLexema(yytext());
                         return token;
          }
        case 94: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
