
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Apr 24 22:30:34 BRT 2019
//----------------------------------------------------

package compiler.syntax;

import java_cup.runtime.Symbol;
import java.util.*;
import es.uned.lsi.compiler.lexical.*;
import es.uned.lsi.compiler.code.*;
import es.uned.lsi.compiler.intermediate.*;
import es.uned.lsi.compiler.semantic.*;
import es.uned.lsi.compiler.semantic.symbol.*;
import es.uned.lsi.compiler.semantic.type.*;
import es.uned.lsi.compiler.syntax.*;
import compiler.CompilerContext;
import compiler.lexical.*;
import compiler.syntax.nonTerminal.*;
import compiler.semantic.*;
import compiler.semantic.symbol.*;
import compiler.semantic.type.*;
import compiler.intermediate.*;
import compiler.code.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed Apr 24 22:30:34 BRT 2019
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\157\000\002\002\004\000\002\056\002\000\002\002" +
    "\004\000\002\003\004\000\002\003\004\000\002\004\005" +
    "\000\002\004\004\000\002\005\013\000\002\005\012\000" +
    "\002\005\010\000\002\006\004\000\002\006\002\000\002" +
    "\006\004\000\002\012\004\000\002\012\003\000\002\013" +
    "\006\000\002\013\005\000\002\014\003\000\002\014\003" +
    "\000\002\007\004\000\002\007\002\000\002\007\004\000" +
    "\002\015\004\000\002\015\003\000\002\016\015\000\002" +
    "\016\005\000\002\010\004\000\002\010\002\000\002\010" +
    "\004\000\002\017\004\000\002\017\003\000\002\020\006" +
    "\000\002\020\005\000\002\021\005\000\002\021\003\000" +
    "\002\022\003\000\002\022\003\000\002\011\005\000\002" +
    "\011\002\000\002\023\007\000\002\023\005\000\002\023" +
    "\004\000\002\025\005\000\002\025\002\000\002\026\005" +
    "\000\002\026\003\000\002\026\002\000\002\027\005\000" +
    "\002\027\005\000\002\024\004\000\002\024\002\000\002" +
    "\024\005\000\002\033\003\000\002\033\003\000\002\033" +
    "\005\000\002\033\003\000\002\034\005\000\002\034\005" +
    "\000\002\034\003\000\002\035\005\000\002\035\005\000" +
    "\002\035\005\000\002\035\004\000\002\035\003\000\002" +
    "\030\004\000\002\030\003\000\002\030\002\000\002\031" +
    "\005\000\002\031\003\000\002\032\003\000\002\032\003" +
    "\000\002\032\003\000\002\032\003\000\002\032\003\000" +
    "\002\032\003\000\002\032\003\000\002\032\003\000\002" +
    "\043\004\000\002\043\005\000\002\042\005\000\002\042" +
    "\005\000\002\044\010\000\002\044\005\000\002\044\005" +
    "\000\002\045\004\000\002\045\002\000\002\046\013\000" +
    "\002\046\012\000\002\046\005\000\002\037\003\000\002" +
    "\037\004\000\002\040\005\000\002\040\004\000\002\040" +
    "\004\000\002\041\005\000\002\041\003\000\002\047\006" +
    "\000\002\047\005\000\002\050\006\000\002\050\005\000" +
    "\002\051\003\000\002\036\003\000\002\036\004\000\002" +
    "\036\004\000\002\052\005\000\002\053\003\000\002\053" +
    "\003\000\002\054\003\000\002\054\003\000\002\055\003" +
    "\000\002\055\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\303\000\004\012\000\001\002\000\004\002\305\001" +
    "\002\000\004\012\007\001\002\000\004\002\uffff\001\002" +
    "\000\006\003\302\004\303\001\002\000\016\003\013\013" +
    "\ufff6\015\ufff6\021\011\022\ufff6\023\ufff6\001\002\000\006" +
    "\003\267\004\270\001\002\000\004\002\ufffe\001\002\000" +
    "\004\002\ufffd\001\002\000\012\013\uffed\015\uffed\022\016" +
    "\023\uffed\001\002\000\010\013\uffe6\015\uffe6\023\044\001" +
    "\002\000\006\003\017\004\020\001\002\000\010\013\uffec" +
    "\015\uffec\023\uffec\001\002\000\006\003\024\045\025\001" +
    "\002\000\012\004\uffea\013\uffea\015\uffea\023\uffea\001\002" +
    "\000\012\004\020\013\uffee\015\uffee\023\uffee\001\002\000" +
    "\012\004\uffeb\013\uffeb\015\uffeb\023\uffeb\001\002\000\004" +
    "\043\043\001\002\000\004\010\026\001\002\000\004\037" +
    "\027\001\002\000\006\004\030\052\032\001\002\000\006" +
    "\040\uff95\041\uff95\001\002\000\004\041\033\001\002\000" +
    "\006\040\uff96\041\uff96\001\002\000\006\004\030\052\032" +
    "\001\002\000\004\040\035\001\002\000\004\011\036\001" +
    "\002\000\006\005\037\006\041\001\002\000\006\036\uff98" +
    "\043\uff98\001\002\000\004\043\042\001\002\000\006\036" +
    "\uff97\043\uff97\001\002\000\012\004\uffe9\013\uffe9\015\uffe9" +
    "\023\uffe9\001\002\000\012\004\uffe8\013\uffe8\015\uffe8\023" +
    "\uffe8\001\002\000\006\003\255\004\240\001\002\000\006" +
    "\013\uffdb\015\046\001\002\000\006\003\222\004\223\001" +
    "\002\000\014\013\ufff6\015\ufff6\021\011\022\ufff6\023\ufff6" +
    "\001\002\000\004\013\051\001\002\000\024\003\071\004" +
    "\073\014\uffbf\016\057\024\063\030\075\032\052\033\070" +
    "\034\055\001\002\000\006\003\214\035\213\001\002\000" +
    "\010\014\uffb8\025\uffb8\043\uffb8\001\002\000\004\014\207" +
    "\001\002\000\010\014\uff9d\025\uff9d\043\uff9d\001\002\000" +
    "\010\014\uffb5\025\uffb5\043\uffb5\001\002\000\020\003\205" +
    "\004\112\020\110\035\103\052\101\053\102\054\104\001" +
    "\002\000\010\014\uffb6\025\uffb6\043\uffb6\001\002\000\006" +
    "\003\200\051\201\001\002\000\010\014\uffc0\025\uffc0\043" +
    "\176\001\002\000\020\003\165\004\112\020\110\035\103" +
    "\052\101\053\102\054\104\001\002\000\010\014\uffbc\025" +
    "\uffbc\043\uffbc\001\002\000\010\014\uffbd\025\uffbd\043\uffbd" +
    "\001\002\000\010\014\uffbb\025\uffbb\043\uffbb\001\002\000" +
    "\010\014\uffba\025\uffba\043\uffba\001\002\000\006\003\157" +
    "\035\160\001\002\000\010\002\ufff8\013\ufff8\015\ufff8\001" +
    "\002\000\010\014\uffb7\025\uffb7\043\uffb7\001\002\000\020" +
    "\003\uff9c\014\uffa8\025\uffa8\035\115\037\114\043\uffa8\051" +
    "\uff9c\001\002\000\010\014\uffb9\025\uffb9\043\uffb9\001\002" +
    "\000\006\003\076\004\077\001\002\000\004\043\155\001" +
    "\002\000\004\051\100\001\002\000\016\004\112\020\110" +
    "\035\103\052\101\053\102\054\104\001\002\000\040\003" +
    "\uffc7\014\uffc7\017\uffc7\025\uffc7\026\uffc7\027\uffc7\031\uffc7" +
    "\036\uffc7\040\uffc7\042\uffc7\043\uffc7\045\uffc7\046\uffc7\047" +
    "\uffc7\050\uffc7\001\002\000\040\003\uff94\014\uff94\017\uff94" +
    "\025\uff94\026\uff94\027\uff94\031\uff94\036\uff94\040\uff94\042" +
    "\uff94\043\uff94\045\uff94\046\uff94\047\uff94\050\uff94\001\002" +
    "\000\016\004\112\020\110\035\103\052\101\053\102\054" +
    "\104\001\002\000\040\003\uff93\014\uff93\017\uff93\025\uff93" +
    "\026\uff93\027\uff93\031\uff93\036\uff93\040\uff93\042\uff93\043" +
    "\uff93\045\uff93\046\uff93\047\uff93\050\uff93\001\002\000\016" +
    "\017\133\031\144\045\127\046\130\047\132\050\131\001" +
    "\002\000\040\003\uffc2\014\uffc2\017\uffc2\025\uffc2\026\uffc2" +
    "\027\uffc2\031\uffc2\036\uffc2\040\uffc2\042\uffc2\043\uffc2\045" +
    "\uffc2\046\uffc2\047\uffc2\050\uffc2\001\002\000\040\003\uffcd" +
    "\014\uffcd\017\uffcd\025\uffcd\026\uffcd\027\uffcd\031\uffcd\036" +
    "\uffcd\040\uffcd\042\uffcd\043\uffcd\045\uffcd\046\uffcd\047\uffcd" +
    "\050\uffcd\001\002\000\016\004\112\020\110\035\103\052" +
    "\101\053\102\054\104\001\002\000\040\003\uffca\014\uffca" +
    "\017\uffca\025\uffca\026\uffca\027\uffca\031\uffca\036\uffca\040" +
    "\uffca\042\uffca\043\uffca\045\uffca\046\uffca\047\uffca\050\uffca" +
    "\001\002\000\044\003\uff9c\014\uff9c\017\uff9c\025\uff9c\026" +
    "\uff9c\027\uff9c\031\uff9c\035\115\036\uff9c\037\114\040\uff9c" +
    "\042\uff9c\043\uff9c\045\uff9c\046\uff9c\047\uff9c\050\uff9c\001" +
    "\002\000\040\003\uffcc\014\uffcc\017\uffcc\025\uffcc\026\uffcc" +
    "\027\uffcc\031\uffcc\036\uffcc\040\uffcc\042\uffcc\043\uffcc\045" +
    "\uffcc\046\uffcc\047\uffcc\050\uffcc\001\002\000\016\004\112" +
    "\020\110\035\103\052\101\053\102\054\104\001\002\000" +
    "\022\003\121\004\112\020\110\035\103\036\123\052\101" +
    "\053\102\054\104\001\002\000\042\003\uff9b\014\uff9b\017" +
    "\uff9b\025\uff9b\026\uff9b\027\uff9b\031\uff9b\036\uff9b\040\uff9b" +
    "\042\uff9b\043\uff9b\045\uff9b\046\uff9b\047\uff9b\050\uff9b\051" +
    "\uff9b\001\002\000\040\003\uff9a\014\uff9a\017\uff9a\025\uff9a" +
    "\026\uff9a\027\uff9a\031\uff9a\036\uff9a\040\uff9a\042\uff9a\043" +
    "\uff9a\045\uff9a\046\uff9a\047\uff9a\050\uff9a\001\002\000\020" +
    "\017\133\036\uffa2\042\uffa2\045\127\046\130\047\132\050" +
    "\131\001\002\000\042\003\uffa4\014\uffa4\017\uffa4\025\uffa4" +
    "\026\uffa4\027\uffa4\031\uffa4\036\uffa4\040\uffa4\042\uffa4\043" +
    "\uffa4\045\uffa4\046\uffa4\047\uffa4\050\uffa4\051\uffa4\001\002" +
    "\000\006\036\125\042\124\001\002\000\042\003\uffa5\014" +
    "\uffa5\017\uffa5\025\uffa5\026\uffa5\027\uffa5\031\uffa5\036\uffa5" +
    "\040\uffa5\042\uffa5\043\uffa5\045\uffa5\046\uffa5\047\uffa5\050" +
    "\uffa5\051\uffa5\001\002\000\016\004\112\020\110\035\103" +
    "\052\101\053\102\054\104\001\002\000\042\003\uffa6\014" +
    "\uffa6\017\uffa6\025\uffa6\026\uffa6\027\uffa6\031\uffa6\036\uffa6" +
    "\040\uffa6\042\uffa6\043\uffa6\045\uffa6\046\uffa6\047\uffa6\050" +
    "\uffa6\051\uffa6\001\002\000\020\017\133\036\uffa3\042\uffa3" +
    "\045\127\046\130\047\132\050\131\001\002\000\016\004" +
    "\112\020\110\035\103\052\101\053\102\054\104\001\002" +
    "\000\016\004\112\020\110\035\103\052\101\053\102\054" +
    "\104\001\002\000\016\004\112\020\110\035\103\052\101" +
    "\053\102\054\104\001\002\000\016\004\112\020\110\035" +
    "\103\052\101\053\102\054\104\001\002\000\016\004\112" +
    "\020\110\035\103\052\101\053\102\054\104\001\002\000" +
    "\040\003\uffc4\014\uffc4\017\uffc4\025\uffc4\026\uffc4\027\uffc4" +
    "\031\uffc4\036\uffc4\040\uffc4\042\uffc4\043\uffc4\045\uffc4\046" +
    "\uffc4\047\132\050\uffc4\001\002\000\040\003\uffc8\014\uffc8" +
    "\017\uffc8\025\uffc8\026\uffc8\027\uffc8\031\uffc8\036\uffc8\040" +
    "\uffc8\042\uffc8\043\uffc8\045\uffc8\046\uffc8\047\uffc8\050\uffc8" +
    "\001\002\000\034\003\uffc6\014\uffc6\017\133\025\uffc6\026" +
    "\uffc6\027\uffc6\031\uffc6\036\uffc6\040\uffc6\042\uffc6\043\uffc6" +
    "\046\130\047\132\001\002\000\040\003\uffc9\014\uffc9\017" +
    "\uffc9\025\uffc9\026\uffc9\027\uffc9\031\uffc9\036\uffc9\040\uffc9" +
    "\042\uffc9\043\uffc9\045\uffc9\046\uffc9\047\132\050\uffc9\001" +
    "\002\000\034\003\uffc5\014\uffc5\017\133\025\uffc5\026\uffc5" +
    "\027\uffc5\031\uffc5\036\uffc5\040\uffc5\042\uffc5\043\uffc5\046" +
    "\130\047\132\001\002\000\016\017\133\040\142\045\127" +
    "\046\130\047\132\050\131\001\002\000\042\003\uff99\014" +
    "\uff99\017\uff99\025\uff99\026\uff99\027\uff99\031\uff99\036\uff99" +
    "\040\uff99\042\uff99\043\uff99\045\uff99\046\uff99\047\uff99\050" +
    "\uff99\051\uff99\001\002\000\040\003\uffc3\014\uffc3\017\uffc3" +
    "\025\uffc3\026\uffc3\027\uffc3\031\uffc3\036\uffc3\040\uffc3\042" +
    "\uffc3\043\uffc3\045\uffc3\046\uffc3\047\uffc3\050\uffc3\001\002" +
    "\000\016\004\112\020\110\035\103\052\101\053\102\054" +
    "\104\001\002\000\020\003\147\017\133\027\146\045\127" +
    "\046\130\047\132\050\131\001\002\000\022\004\073\014" +
    "\uffbf\016\057\024\063\030\075\032\052\033\070\034\055" +
    "\001\002\000\004\043\150\001\002\000\010\014\uffaa\025" +
    "\uffaa\043\uffaa\001\002\000\004\014\152\001\002\000\010" +
    "\014\uffab\025\uffab\043\uffab\001\002\000\016\017\133\036" +
    "\154\045\127\046\130\047\132\050\131\001\002\000\040" +
    "\003\uffcb\014\uffcb\017\uffcb\025\uffcb\026\uffcb\027\uffcb\031" +
    "\uffcb\036\uffcb\040\uffcb\042\uffcb\043\uffcb\045\uffcb\046\uffcb" +
    "\047\uffcb\050\uffcb\001\002\000\010\014\uffa9\025\uffa9\043" +
    "\uffa9\001\002\000\014\003\uff9a\014\uffa7\025\uffa7\043\uffa7" +
    "\051\uff9a\001\002\000\004\043\163\001\002\000\016\004" +
    "\112\020\110\035\103\052\101\053\102\054\104\001\002" +
    "\000\016\017\133\036\162\045\127\046\130\047\132\050" +
    "\131\001\002\000\010\014\uff9f\025\uff9f\043\uff9f\001\002" +
    "\000\010\014\uff9e\025\uff9e\043\uff9e\001\002\000\020\003" +
    "\167\017\133\026\170\045\127\046\130\047\132\050\131" +
    "\001\002\000\004\043\166\001\002\000\010\014\uffae\025" +
    "\uffae\043\uffae\001\002\000\010\014\uffaf\025\uffaf\043\uffaf" +
    "\001\002\000\024\004\073\014\uffbf\016\057\024\063\025" +
    "\uffbf\030\075\032\052\033\070\034\055\001\002\000\006" +
    "\014\uffac\025\173\001\002\000\004\014\175\001\002\000" +
    "\022\004\073\014\uffbf\016\057\024\063\030\075\032\052" +
    "\033\070\034\055\001\002\000\004\014\uffad\001\002\000" +
    "\010\014\uffb0\025\uffb0\043\uffb0\001\002\000\024\004\073" +
    "\014\uffc1\016\057\024\063\025\uffc1\030\075\032\052\033" +
    "\070\034\055\001\002\000\010\014\uffbe\025\uffbe\043\uffbe" +
    "\001\002\000\004\043\203\001\002\000\016\004\112\020" +
    "\110\035\103\052\101\053\102\054\104\001\002\000\022" +
    "\014\uffb2\017\133\025\uffb2\043\uffb2\045\127\046\130\047" +
    "\132\050\131\001\002\000\010\014\uffb1\025\uffb1\043\uffb1" +
    "\001\002\000\022\014\uffb4\017\133\025\uffb4\043\uffb4\045" +
    "\127\046\130\047\132\050\131\001\002\000\004\043\206" +
    "\001\002\000\010\014\uffb3\025\uffb3\043\uffb3\001\002\000" +
    "\006\003\210\004\211\001\002\000\010\002\ufff9\013\ufff9" +
    "\015\ufff9\001\002\000\004\043\212\001\002\000\010\002" +
    "\ufffa\013\ufffa\015\ufffa\001\002\000\004\007\216\001\002" +
    "\000\004\043\215\001\002\000\010\014\uffa0\025\uffa0\043" +
    "\uffa0\001\002\000\004\036\217\001\002\000\010\014\uffa1" +
    "\025\uffa1\043\uffa1\001\002\000\006\013\uffdb\015\046\001" +
    "\002\000\004\013\uffdc\001\002\000\014\013\uffd8\015\uffd8" +
    "\021\uffd8\022\uffd8\023\uffd8\001\002\000\012\003\225\035" +
    "\224\043\uffd6\044\uffd6\001\002\000\006\004\240\036\uffd3" +
    "\001\002\000\014\013\uffd9\015\uffd9\021\uffd9\022\uffd9\023" +
    "\uffd9\001\002\000\006\043\uffcf\044\230\001\002\000\004" +
    "\043\234\001\002\000\010\003\231\005\037\006\041\001" +
    "\002\000\004\043\233\001\002\000\004\043\uffd0\001\002" +
    "\000\004\043\uffce\001\002\000\014\013\uffda\015\uffda\021" +
    "\uffda\022\uffda\023\uffda\001\002\000\006\003\246\044\247" +
    "\001\002\000\006\036\uffd4\043\244\001\002\000\004\036" +
    "\243\001\002\000\010\003\uffdf\042\241\044\uffdf\001\002" +
    "\000\004\004\240\001\002\000\006\003\uffe0\044\uffe0\001" +
    "\002\000\006\043\uffd7\044\uffd7\001\002\000\006\004\240" +
    "\036\uffd3\001\002\000\004\036\uffd5\001\002\000\004\043" +
    "\253\001\002\000\010\004\251\005\037\006\041\001\002" +
    "\000\006\036\uffd2\043\uffd2\001\002\000\006\036\uffdd\043" +
    "\uffdd\001\002\000\006\036\uffde\043\uffde\001\002\000\006" +
    "\036\uffd1\043\uffd1\001\002\000\006\003\261\044\262\001" +
    "\002\000\006\013\uffe5\015\uffe5\001\002\000\010\004\240" +
    "\013\uffe7\015\uffe7\001\002\000\010\004\uffe3\013\uffe3\015" +
    "\uffe3\001\002\000\010\004\uffe4\013\uffe4\015\uffe4\001\002" +
    "\000\004\043\265\001\002\000\010\004\251\005\037\006" +
    "\041\001\002\000\004\043\264\001\002\000\010\004\uffe2" +
    "\013\uffe2\015\uffe2\001\002\000\010\004\uffe1\013\uffe1\015" +
    "\uffe1\001\002\000\014\004\ufff3\013\ufff3\015\ufff3\022\ufff3" +
    "\023\ufff3\001\002\000\012\013\ufff5\015\ufff5\022\ufff5\023" +
    "\ufff5\001\002\000\006\003\273\045\274\001\002\000\014" +
    "\004\270\013\ufff7\015\ufff7\022\ufff7\023\ufff7\001\002\000" +
    "\014\004\ufff4\013\ufff4\015\ufff4\022\ufff4\023\ufff4\001\002" +
    "\000\004\043\301\001\002\000\010\052\275\053\102\054" +
    "\104\001\002\000\004\043\ufff0\001\002\000\004\043\uffef" +
    "\001\002\000\004\043\300\001\002\000\014\004\ufff2\013" +
    "\ufff2\015\ufff2\022\ufff2\023\ufff2\001\002\000\014\004\ufff1" +
    "\013\ufff1\015\ufff1\022\ufff1\023\ufff1\001\002\000\016\003" +
    "\ufffb\013\ufffb\015\ufffb\021\ufffb\022\ufffb\023\ufffb\001\002" +
    "\000\004\043\304\001\002\000\016\003\ufffc\013\ufffc\015" +
    "\ufffc\021\ufffc\022\ufffc\023\ufffc\001\002\000\004\002\001" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\303\000\006\002\003\056\004\001\001\000\002\001" +
    "\001\000\006\003\005\004\007\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\005\011\006\013\001\001\000" +
    "\006\012\270\013\265\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\007\014\001\001\000\004\010\044\001" +
    "\001\000\006\015\021\016\020\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\016\022\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\054\030\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\054\033" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\053" +
    "\037\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\017" +
    "\255\020\256\021\253\001\001\000\006\011\047\023\046" +
    "\001\001\000\002\001\001\000\006\005\217\006\013\001" +
    "\001\000\002\001\001\000\032\030\053\031\061\032\064" +
    "\036\060\037\055\042\063\043\073\044\065\046\066\047" +
    "\052\050\071\051\057\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\033\203\034\106\035\112\036\110\055\105" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\033\163\034\106\035\112\036\110\055\105" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\040\155\052\115\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\033\104\034\106\035\112\036\110\055" +
    "\105\001\001\000\002\001\001\000\002\001\001\000\014" +
    "\033\152\034\106\035\112\036\110\055\105\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\033\142\034\106\035\112\036\110\055" +
    "\105\001\001\000\002\001\001\000\006\040\116\052\115" +
    "\001\001\000\002\001\001\000\014\033\140\034\106\035" +
    "\112\036\110\055\105\001\001\000\016\033\117\034\106" +
    "\035\112\036\110\041\121\055\105\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\033\125\034" +
    "\106\035\112\036\110\055\105\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\033\137\034\106\035\112\036" +
    "\110\055\105\001\001\000\014\033\136\034\106\035\112" +
    "\036\110\055\105\001\001\000\014\033\135\034\106\035" +
    "\112\036\110\055\105\001\001\000\014\033\134\034\106" +
    "\035\112\036\110\055\105\001\001\000\014\033\133\034" +
    "\106\035\112\036\110\055\105\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\033\144\034\106\035\112\036\110\055" +
    "\105\001\001\000\002\001\001\000\032\030\150\031\061" +
    "\032\064\036\060\037\055\042\063\043\073\044\065\046" +
    "\066\047\052\050\071\051\057\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\033\160\034\106\035" +
    "\112\036\110\055\105\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\032\030\170" +
    "\031\061\032\064\036\060\037\055\042\063\043\073\044" +
    "\065\046\066\047\052\050\071\051\057\001\001\000\004" +
    "\045\171\001\001\000\002\001\001\000\032\030\173\031" +
    "\061\032\064\036\060\037\055\042\063\043\073\044\065" +
    "\046\066\047\052\050\071\051\057\001\001\000\002\001" +
    "\001\000\002\001\001\000\026\032\176\036\060\037\055" +
    "\042\063\043\073\044\065\046\066\047\052\050\071\051" +
    "\057\001\001\000\002\001\001\000\002\001\001\000\014" +
    "\033\201\034\106\035\112\036\110\055\105\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\011\220\023\046\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\025\225\001\001\000" +
    "\010\021\234\026\236\027\235\001\001\000\002\001\001" +
    "\000\004\024\226\001\001\000\002\001\001\000\004\053" +
    "\231\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\021\241" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\021" +
    "\234\026\244\027\235\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\022\247\053\251\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\020\257\021" +
    "\253\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\022\262\053\251\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\013\271\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\014\276" +
    "\055\275\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	SyntaxErrorManager syntaxErrorManager = CompilerContext.getSyntaxErrorManager();
	
	public void syntax_error(Symbol symbol)
	{ 
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxError ("Error sintactico", token);	    
	}
		
	public void unrecovered_syntax_error(java_cup.runtime.Symbol symbol)
	{	
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxFatalError ("Error fatal", token);
	}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


	
	SyntaxErrorManager   syntaxErrorManager   = CompilerContext.getSyntaxErrorManager();
	SemanticErrorManager semanticErrorManager = CompilerContext.getSemanticErrorManager ();
	ScopeManagerIF       scopeManager         = CompilerContext.getScopeManager ();
	FinalCodeFactoryIF   finalCodeFactory     = CompilerContext.getFinalCodeFactory ();


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 110: // vBooleano ::= FALSE 
            {
              VBooleano RESULT =null;
		
                   RESULT = new VBooleano(false);
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("vBooleano",43, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 109: // vBooleano ::= TRUE 
            {
              VBooleano RESULT =null;
		
                   RESULT = new VBooleano(true);
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("vBooleano",43, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 108: // entOid ::= IDENTIFICADOR 
            {
              EntOId RESULT =null;
		int identificadorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int identificadorright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token identificador = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT = new EntOId(identificador.getLexema());
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("entOid",42, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 107: // entOid ::= ENTERO 
            {
              EntOId RESULT =null;
		int enteroleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int enteroright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token entero = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT = new EntOId(Integer.parseInt(entero.getLexema()));
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("entOid",42, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 106: // intOBool ::= BOOLEAN 
            {
              IntOBool RESULT =null;
		
                    RESULT =  new IntOBool("BOOL");
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("intOBool",41, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 105: // intOBool ::= INTEGER 
            {
              IntOBool RESULT =null;
		
                    RESULT =  new IntOBool("INTEGER");
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("intOBool",41, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 104: // idArray ::= CORCHIZQ expresion CORCHDER 
            {
              IdArray RESULT =null;
		int expresionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int expresionright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expresion expresion = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                    RESULT = new IdArray(expresion);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("idArray",40, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 103: // variables ::= IDENTIFICADOR parFuncion 
            {
              Variables RESULT =null;
		int parFuncionleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int parFuncionright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ParFuncion parFuncion = (ParFuncion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT = new Variables(parFuncion);
                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("variables",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 102: // variables ::= IDENTIFICADOR idArray 
            {
              Variables RESULT =null;
		int idArrayleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idArrayright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		IdArray idArray = (IdArray)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT = new Variables(idArray);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("variables",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // variables ::= IDENTIFICADOR 
            {
              Variables RESULT =null;
		int identificadorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int identificadorright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token identificador = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT = new Variables(identificador.getLexema());
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("variables",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // sWriteLn ::= WRITELN 
            {
              SWriteLn RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sWriteLn",39, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // sWriteInt ::= WRITEINT error PUNTOYCOMA 
            {
              SWriteInt RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sWriteInt",38, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // sWriteInt ::= WRITEINT PARENIZQ expresion PARENDER 
            {
              SWriteInt RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sWriteInt",38, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // sWriteString ::= WRITESTRING error PUNTOYCOMA 
            {
              SWriteString RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sWriteString",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // sWriteString ::= WRITESTRING PARENIZQ STRING PARENDER 
            {
              SWriteString RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sWriteString",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // parametros ::= expresion 
            {
              Parametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // parametros ::= parametros COMA expresion 
            {
              Parametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // parFuncion ::= PARENIZQ error 
            {
              ParFuncion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parFuncion",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // parFuncion ::= PARENIZQ PARENDER 
            {
              ParFuncion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parFuncion",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // parFuncion ::= PARENIZQ parametros PARENDER 
            {
              ParFuncion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parFuncion",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // sentProcedure ::= IDENTIFICADOR parFuncion 
            {
              SentProcedure RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentProcedure",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // sentProcedure ::= IDENTIFICADOR 
            {
              SentProcedure RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentProcedure",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // sentFor ::= FOR error PUNTOYCOMA 
            {
              SentFor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentFor",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // sentFor ::= FOR IDENTIFICADOR DOSPUNTOSIGUAL expresion TO expresion error PUNTOYCOMA 
            {
              SentFor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentFor",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // sentFor ::= FOR IDENTIFICADOR DOSPUNTOSIGUAL expresion TO expresion DO sentencias END 
            {
              SentFor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentFor",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // sentElse ::= 
            {
              SentElse RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentElse",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // sentElse ::= ELSE sentencias 
            {
              SentElse RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentElse",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // sentIf ::= IF error PUNTOYCOMA 
            {
              SentIf RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentIf",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // sentIf ::= IF expresion error 
            {
              SentIf RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentIf",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // sentIf ::= IF expresion THEN sentencias sentElse END 
            {
              SentIf RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentIf",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // sentAsign ::= variables error PUNTOYCOMA 
            {
              SentAsign RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentAsign",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // sentAsign ::= variables DOSPUNTOSIGUAL expresion 
            {
              SentAsign RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentAsign",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // sentReturn ::= RETURN error PUNTOYCOMA 
            {
              SentReturn RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentReturn",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // sentReturn ::= RETURN expresion 
            {
              SentReturn RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentReturn",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // sentencia ::= sentProcedure 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // sentencia ::= sWriteLn 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // sentencia ::= sWriteInt 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // sentencia ::= sWriteString 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // sentencia ::= sentReturn 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // sentencia ::= sentFor 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // sentencia ::= sentIf 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // sentencia ::= sentAsign 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // listSentencia ::= sentencia 
            {
              ListSentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listSentencia",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // listSentencia ::= listSentencia PUNTOYCOMA sentencia 
            {
              ListSentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listSentencia",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // sentencias ::= 
            {
              Sentencias RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencias",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // sentencias ::= listSentencia 
            {
              Sentencias RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencias",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // sentencias ::= listSentencia PUNTOYCOMA 
            {
              Sentencias RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencias",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // exprLogica ::= vBooleano 
            {
              ExprLogica RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprLogica",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // exprLogica ::= NOT expresion 
            {
              ExprLogica RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprLogica",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // exprLogica ::= expresion OR expresion 
            {
              ExprLogica RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprLogica",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // exprLogica ::= expresion IGUAL expresion 
            {
              ExprLogica RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprLogica",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // exprLogica ::= expresion MAYOR expresion 
            {
              ExprLogica RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprLogica",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // exprArit ::= ENTERO 
            {
              ExpArit RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprArit",26, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // exprArit ::= expresion PRODUCTO expresion 
            {
              ExpArit RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprArit",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // exprArit ::= expresion MINUS expresion 
            {
              ExpArit RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("exprArit",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresion ::= variables 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresion ::= PARENIZQ expresion PARENDER 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresion ::= exprLogica 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresion ::= exprArit 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // tipoRetorno ::= DOSPUNTOS error PUNTOYCOMA 
            {
              TipoRetorno RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoRetorno",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // tipoRetorno ::= 
            {
              TipoRetorno RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoRetorno",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // tipoRetorno ::= DOSPUNTOS intOBool 
            {
              TipoRetorno RESULT =null;
		int intOBoolleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int intOBoolright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		IntOBool intOBool = (IntOBool)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT = new TipoRetorno(intOBool);
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoRetorno",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // procParam ::= cadIdVar error PUNTOYCOMA 
            {
              ProcParam RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("procParam",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // procParam ::= cadIdVar DOSPUNTOS tipoVar 
            {
              ProcParam RESULT =null;
		int cadIdVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cadIdVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		CadIdVar cadIdVar = (CadIdVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tipoVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tipoVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TipoVar tipoVar = (TipoVar)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  RESULT = new ProcParam(cadIdVar, tipoVar);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("procParam",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // procListParam ::= 
            {
              ProcListParam RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("procListParam",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // procListParam ::= procParam 
            {
              ProcListParam RESULT =null;
		int procParamleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int procParamright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ProcParam procParam = (ProcParam)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                 RESULT = new ProcListParam(procParam);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("procListParam",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // procListParam ::= procParam PUNTOYCOMA procListParam 
            {
              ProcListParam RESULT =null;
		int procParamleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int procParamright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ProcParam procParam = (ProcParam)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int procListParamleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int procListParamright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ProcListParam procListParam = (ProcListParam)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                 procListParam.addProcParam(procParam);
                 RESULT = procListParam;
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("procListParam",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // procParenParam ::= 
            {
              ProcParenParam RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("procParenParam",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // procParenParam ::= PARENIZQ procListParam PARENDER 
            {
              ProcParenParam RESULT =null;
		int procListParamleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int procListParamright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ProcListParam procListParam = (ProcListParam)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                 RESULT = new ProcParenParam(procListParam);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("procParenParam",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // cabProcedure ::= PROCEDURE error 
            {
              CabProcedure RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabProcedure",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // cabProcedure ::= PROCEDURE IDENTIFICADOR error 
            {
              CabProcedure RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabProcedure",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // cabProcedure ::= PROCEDURE IDENTIFICADOR procParenParam tipoRetorno PUNTOYCOMA 
            {
              CabProcedure RESULT =null;
		int identificadorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int identificadorright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Token identificador = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int procParenParamleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int procParenParamright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ProcParenParam procParenParam = (ProcParenParam)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tipoRetornoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tipoRetornoright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		TipoRetorno tipoRetorno = (TipoRetorno)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                   RESULT = new CabProcedure(identificador.getLexema(), procParenParam, tipoRetorno);
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabProcedure",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // stmSubprogram ::= 
            {
              StmSubprogram RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmSubprogram",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // stmSubprogram ::= cabProcedure cuerpo stmSubprogram 
            {
              StmSubprogram RESULT =null;
		int cabProcedureleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int cabProcedureright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		CabProcedure cabProcedure = (CabProcedure)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int cuerpoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int cuerporight = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Cuerpo cuerpo = (Cuerpo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int stmSubprogramleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int stmSubprogramright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		StmSubprogram stmSubprogram = (StmSubprogram)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  stmSubprogram.addCuerpoAndProcedure(cuerpo, cabProcedure);
                  RESULT = stmSubprogram;
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmSubprogram",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // tipoVar ::= IDENTIFICADOR 
            {
              TipoVar RESULT =null;
		int identificadorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int identificadorright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token identificador = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT = new TipoVar(identificador.getLexema());
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoVar",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // tipoVar ::= intOBool 
            {
              TipoVar RESULT =null;
		int intOBoolleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int intOBoolright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		IntOBool intOBool = (IntOBool)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT = new TipoVar(intOBool);
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoVar",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // cadIdVar ::= IDENTIFICADOR 
            {
              CadIdVar RESULT =null;
		int identificadorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int identificadorright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token identificador = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  RESULT =  new CadIdVar(identificador.getLexema());
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cadIdVar",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // cadIdVar ::= IDENTIFICADOR COMA cadIdVar 
            {
              CadIdVar RESULT =null;
		int identificadorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int identificadorright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Token identificador = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int cadIdVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int cadIdVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		CadIdVar cadIdVar = (CadIdVar)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  cadIdVar.addIdentificador(identificador.getLexema());
                  RESULT = cadIdVar;
                 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cadIdVar",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expVar ::= cadIdVar error PUNTOYCOMA 
            {
              ExpVar RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expVar",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expVar ::= cadIdVar DOSPUNTOS tipoVar PUNTOYCOMA 
            {
              ExpVar RESULT =null;
		int cadIdVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int cadIdVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		CadIdVar cadIdVar = (CadIdVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int tipoVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tipoVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		TipoVar tipoVar = (TipoVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                   RESULT = new ExpVar(cadIdVar, tipoVar);
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expVar",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // sentVar ::= expVar 
            {
              SentVar RESULT =null;
		int expVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int expVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ExpVar expVar = (ExpVar)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT = new SentVar(expVar);
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentVar",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sentVar ::= sentVar expVar 
            {
              SentVar RESULT =null;
		int sentVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sentVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		SentVar sentVar = (SentVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int expVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int expVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ExpVar expVar = (ExpVar)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     sentVar.addExpVar(expVar);
                     RESULT = sentVar;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentVar",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // stmVar ::= VAR error 
            {
              StmVar RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmVar",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // stmVar ::= 
            {
              StmVar RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmVar",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // stmVar ::= VAR sentVar 
            {
              StmVar RESULT =null;
		int sentVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sentVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		SentVar sentVar = (SentVar)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT = new StmVar(sentVar);
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmVar",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expTipo ::= IDENTIFICADOR error PUNTOYCOMA 
            {
              ExpTipo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expTipo",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expTipo ::= IDENTIFICADOR IGUAL ARRAY CORCHIZQ entOid PUNTOPUNTO entOid CORCHDER OF intOBool PUNTOYCOMA 
            {
              ExpTipo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expTipo",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // sentTipo ::= expTipo 
            {
              SentTipo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentTipo",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // sentTipo ::= sentTipo expTipo 
            {
              SentTipo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentTipo",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // stmTipos ::= TYPE error 
            {
              StmTipos RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmTipos",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // stmTipos ::= 
            {
              StmTipos RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmTipos",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // stmTipos ::= TYPE sentTipo 
            {
              StmTipos RESULT =null;
		int sentTipoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sentTiporight = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		SentTipo sentTipo = (SentTipo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                  RESULT = new StmTipos(sentTipo);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmTipos",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // valorConst ::= vBooleano 
            {
              ValorConst RESULT =null;
		int vBooleanoleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vBooleanoright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		VBooleano vBooleano = (VBooleano)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                   ValorConst valorConst = new ValorConst(vBooleano.getValue());
                   RESULT = valorConst;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorConst",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // valorConst ::= ENTERO 
            {
              ValorConst RESULT =null;
		int valorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valorright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token valor = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                   ValorConst valorConst = new ValorConst(Integer.parseInt(valor.getLexema()));
                   RESULT = valorConst;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorConst",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expConst ::= IDENTIFICADOR error PUNTOYCOMA 
            {
              ExpConst RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expConst",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expConst ::= IDENTIFICADOR IGUAL valorConst PUNTOYCOMA 
            {
              ExpConst RESULT =null;
		int identificadorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int identificadorright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Token identificador = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int valorConstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int valorConstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ValorConst valorConst = (ValorConst)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                   String expConstIdentificador = identificador.getLexema();
                   ExpConst expConst = new ExpConst(expConstIdentificador, valorConst);
                   RESULT = expConst;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expConst",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // sentConst ::= expConst 
            {
              SentConst RESULT =null;
		int expConstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int expConstright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ExpConst expConst = (ExpConst)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                     RESULT = new SentConst(expConst);
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentConst",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // sentConst ::= sentConst expConst 
            {
              SentConst RESULT =null;
		int sentConstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int sentConstright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		SentConst sentConst = (SentConst)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int expConstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int expConstright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ExpConst expConst = (ExpConst)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    sentConst.addExpConst(expConst);
                    RESULT = sentConst;
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentConst",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // stmConstantes ::= CONST error 
            {
              StmConstantes RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmConstantes",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmConstantes ::= 
            {
              StmConstantes RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmConstantes",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmConstantes ::= CONST sentConst 
            {
              StmConstantes RESULT =null;
		int sentConstleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sentConstright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		SentConst sentConst = (SentConst)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                   RESULT = new StmConstantes(sentConst);
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmConstantes",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // cuerpo ::= stmConstantes stmTipos stmVar stmSubprogram BEGIN error 
            {
              Cuerpo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cuerpo",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // cuerpo ::= stmConstantes stmTipos stmVar stmSubprogram BEGIN sentencias END error 
            {
              Cuerpo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cuerpo",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // cuerpo ::= stmConstantes stmTipos stmVar stmSubprogram BEGIN sentencias END IDENTIFICADOR PUNTOYCOMA 
            {
              Cuerpo RESULT =null;
		int stmConstantesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).left;
		int stmConstantesright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)).right;
		StmConstantes stmConstantes = (StmConstantes)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-8)).value;
		int stmTiposleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).left;
		int stmTiposright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)).right;
		StmTipos stmTipos = (StmTipos)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-7)).value;
		int stmVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int stmVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		StmVar stmVar = (StmVar)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int stmSubprogramleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int stmSubprogramright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		StmSubprogram stmSubprogram = (StmSubprogram)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int sentenciasleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int sentenciasright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		Sentencias sentencias = (Sentencias)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		
                   RESULT = new Cuerpo(stmConstantes, stmTipos, stmVar, stmSubprogram, sentencias);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cuerpo",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // cabModule ::= MODULE error 
            {
              CabModule RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabModule",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // cabModule ::= MODULE IDENTIFICADOR PUNTOYCOMA 
            {
              CabModule RESULT =null;
		int identificadorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int identificadorright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Token identificador = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                    RESULT = new CabModule(identificador.getLexema());
                  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("cabModule",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // axiom ::= cabModule error 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // axiom ::= cabModule cuerpo 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= NT$0 axiom 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int axleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int axright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Axiom ax = (Axiom)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
  		// No modificar esta estructura, aunque se pueden añadir más acciones semánticas
  		
  		//List intermediateCode = ax.getIntermediateCode ();
  		//finalCodeFactory.create (intermediateCode);

  		// En caso de no comentarse las dos sentencias anteriores puede generar una excepcion
  		// en las llamadas a cupTest si el compilador no está completo. Esto es debido a que 
  		// aún no se tendrá implementada la generación de código intermedio ni final.
  		// Para la entrega final deberán descomentarse y usarse.
  		syntaxErrorManager.syntaxInfo ("Parsing process ended.");
  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT =null;
 
      syntaxErrorManager.syntaxInfo ("Starting parsing..."); 
  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

