
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 11 20:55:20 BRT 2019
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int DOSPUNTOS = 34;
  public static final int CONST = 15;
  public static final int PUNTOYCOMA = 33;
  public static final int ENTERO = 40;
  public static final int INTEGER = 3;
  public static final int PARENIZQ = 27;
  public static final int ARRAY = 6;
  public static final int WRITEINT = 25;
  public static final int MINUS = 36;
  public static final int FOR = 22;
  public static final int IDENTIFICADOR = 2;
  public static final int NOT = 14;
  public static final int IGUAL = 35;
  public static final int CORCHIZQ = 29;
  public static final int TYPE = 16;
  public static final int OR = 13;
  public static final int BEGIN = 9;
  public static final int DOSPUNTOSIGUAL = 39;
  public static final int IF = 18;
  public static final int WRITELN = 26;
  public static final int OF = 7;
  public static final int EOF = 0;
  public static final int BOOLEAN = 4;
  public static final int PRODUCTO = 37;
  public static final int RETURN = 12;
  public static final int TRUE = 41;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int PARENDER = 28;
  public static final int PUNTOPUNTO = 31;
  public static final int MAYOR = 38;
  public static final int MODULE = 8;
  public static final int ELSE = 19;
  public static final int CORCHDER = 30;
  public static final int WRITESTRING = 24;
  public static final int TO = 23;
  public static final int THEN = 20;
  public static final int END = 10;
  public static final int STRING = 5;
  public static final int FALSE = 42;
  public static final int VAR = 17;
  public static final int PROCEDURE = 11;
  public static final int DO = 21;
}

